name: Deploy VitePress Docs to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'Dockerfile.docs.prod'
      - 'nginx.docs.conf.template'
      - 'docker-entrypoint.docs.sh'
      - '.github/workflows/deploy-docs.yml'
  workflow_dispatch:  # 允許手動觸發

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: ecommerce-docs
  REGION: asia-east1
  IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/ecommerce-docs

jobs:
  deploy:
    name: Build and Deploy VitePress Docs to Cloud Run
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout 代碼
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 設置 Google Cloud CLI
      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      # 3. 配置 Docker 認證到 GCR
      - name: Configure Docker to use gcloud
        run: gcloud auth configure-docker

      # 4. 構建 Docker 映像（VitePress 多階段建置）
      - name: Build Docker image
        run: |
          docker build \
            -f Dockerfile.docs.prod \
            -t ${{ env.IMAGE_NAME }}:${{ github.sha }} \
            -t ${{ env.IMAGE_NAME }}:latest \
            .

      # 5. 推送映像到 Google Container Registry
      - name: Push Docker image to GCR
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.IMAGE_NAME }}:latest

      # 6. 部署到 Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image=${{ env.IMAGE_NAME }}:${{ github.sha }} \
            --platform=managed \
            --region=${{ env.REGION }} \
            --allow-unauthenticated \
            --port=8080 \
            --cpu=1 \
            --memory=512Mi \
            --min-instances=0 \
            --max-instances=5

      # 7. 輸出部署 URL
      - name: Output deployment URL
        run: |
          echo "✅ VitePress Docs deployment completed!"
          gcloud run services describe ${{ env.SERVICE_NAME }} \
            --platform=managed \
            --region=${{ env.REGION }} \
            --format='value(status.url)'
